name: Repo Compare
description: Compare Repos
branding:
  icon: 'git-branch'
  color: 'gray-dark'
inputs:
  source_repo:
    description: GitHub public repo slug or full https clone url (with access_token if needed)
    required: true
  destination_repo:
    description: Repo name to sync to in this repo. default to who runed this action.
    default: '${{ github.repository }}'
    required: false
  source_branch:
    description: Branch name to sync from
    required: false
  destination_branch:
    description: Branch name to sync to in this repo
    required: false
  sync_tags:
    description: Should tags also be synced
    required: false
  destination_repo_from_file:
    description: Set to true if destination_repo specs a file that contains latest result of `git ls-remote`
    required: false
outputs:
  result:
    description: result of compare
    value: ${{ steps.cmp.outputs.result }}
runs:
  using: 'composite'
  steps:
    - id: cmp
      shell: bash
      run: |
        sh="${{ github.action_path }}/repo-cmp.sh"
        chmod +x $sh
        $sh

