name: Repo Compare
description: Compare Repos
branding:
  icon: 'git-branch'
  color: 'gray-dark'
inputs:
  source_repo:
    description: GitHub public repo slug or full https clone url (with access_token if needed)
    required: true
  destination_repo:
    description: Repo name to sync to in this repo. default to who runed this action.
    required: false
  source_branch:
    description: Branch name to sync from
    required: true
  destination_branch:
    description: Branch name to sync to in this repo
    required: true
  sync_tags:
    description: Should tags also be synced
    required: false
outputs:
  result:
    description: result of compare
    value: ${{ steps.cmp.outputs.result }}
runs:
  using: 'composite'
  steps:
    - id: cmp
      shell: bash
      run: |
        echo 'Getting remotes'
        source_raw=`git ls-remote '${{ input.source_repo }}' /refs/heads/*`
        echo $source_raw